### PR TITLE
Fix Trace search time is null ,there is an error

### PR DESCRIPTION
**Pull request by candyleer**
If Trace search  time is null ,there is an error.
1.  so be compatible with this error
2. delete the time, we can get the newest trace instead of refresh the page to get. it is not convenient for end users now if user want to get the newest trace data.

image

### CODE REVIEW

**Comment by hanahmily** [comment]
You can refer to[AntD Form Validation](https://ant.design/components/form/#components-form-demo-validate-static) to fix it.

**Comment by candyleer** [comment]
this looks good for this validation.
 but another question. actually I want to a way to fetch the newest traces in a more convenient  way instead of refresh the page(looks loading a bit slow, so I don't want to use ) or modify the date then click `search` button.

**Comment by wu-sheng** [comment]
> but another question. actually I want to a way to fetch the newest traces in a more convenient way instead of refresh the page(looks loading a bit slow, so I don't want to use ) or modify the date then click search button.

Do you have any proposal?

**Comment by candyleer** [comment]
add a radio to view `Latest 15 minutes`(`select` component?) data or use data range search ?

**Comment by wu-sheng** [comment]
> Latest 15 minutes

This could be a new feature.

> select component

This is hard, I think. The trace query is based service entrances, e.g. HTTP URLs, RPC service class name.

> use data range search 

How data range?

**Comment by candyleer** [comment]
haha , `data range` is a mistake..it's date
a prototype about what i say 
image

**Comment by wu-sheng** [comment]
Last 15 mins for quick search works for me. Info you that, we will add more links for trace query in beta2, which will let the users don't need to select/query traces manually.

The UI will guide the users to there.

**Comment by candyleer** [comment]
that's great

**Comment by wu-sheng** [comment]
@hanahmily Even the pr is good enough, please hold this for beta2. We must make sure the codes froze.

FYI @candyleer

**Comment by wu-sheng** [comment]
@hanahmily I have to change the milestone and move this into beta release. Please be advised. Codes should be frozen by now.

**Pull request merged**
