### PR TITLE
Feature: update spans display

### PR DESCRIPTION
**Pull request by TinyAllen**
1.Add top childrens and top slow span.
2.fix windowresize bug.
3.fix time and span tiptip connection.
4.Optimized tree rendering algorithm.

### CODE REVIEW

**Comment by TinyAllen** [comment]
wx20181227-000307 2x
wx20181227-000320 2x

**Comment by wu-sheng** [comment]
I have two suggestions
1. TopSlow should be 'Top 5 of slow span', also in this mode, span duration could show itself only, not include children spans. Because you calculate the list by this way.
1. TopSpan should be 'Top 5 of children span number'. And show the child spans number, only if possible, this is not as important as span duration.

**Comment by TinyAllen** [comment]
wx20181227-173153 2x 1

**Comment by wu-sheng** [comment]
Cool. Like this

**Comment by wu-sheng** [comment]
I will write an English and Chinese document for this new page.

**Comment by TinyAllen** [comment]
😄thanks！

**Comment by wu-sheng** [comment]
Please send a pull request to sync main repo. @TinyAllen

**Pull request merged**
